name: Deploy Static Site

on: push

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Ensure tokens.js is ignored by Git
      - name: Ensure tokens.js is ignored by Git
        run: |
          echo "tokens.js" >> .gitignore
          git add .gitignore
          git commit -m "Ensure tokens.js is ignored"
          git push
        shell: bash

      # Remove old tokens file (if exists)
      - name: Remove old tokens file (if exists)
        run: |
          if [ -f tokens.js ]; then
            echo "Removing old tokens.js file"
            rm tokens.js
          else
            echo "No existing tokens.js file to remove"
          fi
        shell: bash

      # Create new tokens file
      - name: Create new tokens file
        run: |
          echo "export const validTokens = ['${{ secrets.SECRET_API_TOKEN }}'];" > ./tokens.js
          echo "New tokens.js file created:"
          cat tokens.js
        shell: bash

      - name: List files after creating tokens.js
        run: |
          ls -la
        shell: bash

      # List files before deployment
      - name: List files before deployment
        run: |
          pwd
          ls -la
        shell: bash

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Update to your build output directory if needed
          destination_dir: .

      # Verify deployment (optional)
      - name: Verify deployment
        run: |
          echo "Deployment completed"
        shell: bash
