name: Deploy Static Site

on: push

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Remove old tokens.js file (if exists)
      - name: Remove old tokens.js file (if exists)
        run: |
          if [ -f tokens.js ]; then
            echo "Removing old tokens.js file"
            rm tokens.js
          else
            echo "No existing tokens.js file to remove"
          fi
        shell: bash

      # Create new tokens.js file (This file will not be tracked by git)
      - name: Create new tokens.js file
        run: |
          echo "export const validTokens = ['${{ secrets.SECRET_API_TOKEN }}'];" > ./tokens.js
          echo "New tokens.js file created:"
          cat tokens.js
        shell: bash

      # Temporarily remove tokens.js from .gitignore
      - name: Temporarily remove tokens.js from .gitignore
        run: |
          sed -i '/tokens.js/d' .gitignore
        shell: bash

      # List files after creating tokens.js
      - name: List files after creating tokens.js
        run: |
          ls -la
        shell: bash

      # List files before deployment
      - name: List files before deployment
        run: |
          pwd
          ls -la
        shell: bash

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Make sure this is the correct directory where your `index.html` is
          destination_dir: .

      # Add tokens.js back to .gitignore
      - name: Add tokens.js back to .gitignore
        run: |
          echo "tokens.js" >> .gitignore
        shell: bash

      # Verify deployment
      - name: Verify deployment
        run: |
          echo "Deployment completed"
        shell: bash
