name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Create Config File
        run: |
          # Explicitly create tokens.js
          echo "// Generated Configuration" > tokens.js
          echo "window.CONFIG = {" >> tokens.js
          echo "  API_TOKEN: '${{ secrets.SECRET_API_TOKEN }}'," >> tokens.js
          echo "};" >> tokens.js
          
          # Show file contents for verification
          echo "Config file contents:"
          cat tokens.js
        shell: bash
      
      - name: List Files
        run: |
          echo "Listing files before deployment:"
          ls -la
        shell: bash
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Deploy entire repository
          force: true # Force push if needed