name: Deploy Static Site

on:
  push:
    branches:
      - main  # Adjust the branch as necessary

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Remove old tokens.js file (if exists)
      - name: Remove old tokens.js file (if exists)
        run: |
          if [ -f tokens.js ]; then
            echo "Removing old tokens.js file"
            rm tokens.js
          else
            echo "No existing tokens.js file to remove"
          fi
        shell: bash

      # Create new tokens.js file (without committing it)
      - name: Create new tokens.js file
        run: |
          echo "export const validTokens = ['${{ secrets.SECRET_API_TOKEN }}'];" > tokens.js
          echo "New tokens.js file created"
        shell: bash

      # Temporarily add tokens.js to Git to commit it to deploy
      - name: Temporarily add tokens.js to Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add tokens.js
          git commit -m "Add tokens.js for deployment"
        shell: bash
        continue-on-error: true # Allow failure if no changes are made

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # This assumes all files (index.html, etc.) are in the root directory
          destination_dir: .

      # Remove tokens.js from Git (ensure it's not committed)
      - name: Remove tokens.js from Git
        run: |
          git rm tokens.js
          git commit -m "Remove tokens.js after deployment"
          git push origin HEAD:main
        shell: bash

      # Verify deployment
      - name: Verify deployment
        run: |
          echo "Deployment completed"
        shell: bash
