name: Deploy Static Site with Node.js

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Inject Secrets and Build Static Site
        env:
          API_URL: ${{ secrets.API_URL }}
          FEATURE_FLAG: ${{ secrets.FEATURE_FLAG }}
          SECRET_API_TOKEN: ${{ secrets.SECRET_API_TOKEN }}
        run: |
          node build.js  # This will inject the secrets into your static files

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # This is where your built files should be located
