name: Deploy Static Site with Tokens

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and bundle your application
        run: |
          echo "export const validTokens = ['${{ secrets.SECRET_API_TOKEN }}'];" > tokens.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Replace with your actual build directory
          exclude_files: tokens.js # Exclude tokens.js from deployment
          destination_dir: . # Deploy to the root of the GitHub Pages branch

      - name: Verify deployment
        run: |
          echo "Deployment completed"
        shell: bash