name: Deploy Plain HTML/JS App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Create the tokens.js file dynamically
      - name: Create tokens.js
        run: |
          echo "export const tokens = ['${{ secrets.SECRET_API_TOKEN }}'];" > tokens.js

      # Step 3: Add the tokens.js file to the build directory
      - name: Add tokens.js to the build
        run: |
          mv tokens.js .

      # Step 4: Deploy the build (to GitHub Pages or another host)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Adjust to the directory containing your HTML/JS files
