name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Test Secret Access
        run: echo "Secret is set"
        env:
          SECRET_API_TOKEN: ${{ secrets.SECRET_API_TOKEN }}
