name: Example GitHub Action

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use secret API token
        run: |
          echo "Using the secret API token..."
          curl -X GET "https://api.example.com/data" -H "Authorization: Bearer ${{ secrets.SECRET_API_TOKEN }}"
