name: Deploy Static Site

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Replace Secret
        env:
          API_TOKEN: ${{ secrets.SECRET_API_TOKEN }}
        run: |
          sed -i "s|{{SECRET_API_TOKEN}}|$API_TOKEN|g" index.html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
