name: Example API Workflow

on:
  workflow_dispatch: # Allows manual trigger via API

jobs:
  api_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call external API with SECRET_API_TOKEN
        run: |
          echo "${{ secrets.SECRET_API_TOKEN }}"
          # Your API call logic here
